version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lol-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["php-fpm"]
    depends_on:
      - db
    networks:
      - lol-network

  webserver:
    image: nginx:alpine
    container_name: lol-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - lol-network

  db:
    image: postgres:15
    container_name: lol-pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: loltracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lol-network

networks:
  lol-network:

volumes:
  pgdata: